### ISSUE TITLE
gem5 - amdgpu

### ISSUE THREAD

**Issue by AIFanatic** [geohot/7900xtx#10]
Found this: http://doxygen.gem5.org/develop/structgem5_1_1GEM5__PACKED.html
PQ=PrimaryQueue?

GEM5: "The gem5 simulator is a modular platform for computer-system architecture research"

They seem to have some interesting stuff on the repo too: https://github.com/gem5/gem5/blob/stable/src/dev/amdgpu/pm4_packet_processor.cc
https://www.gem5.org/documentation/general_docs/gpu_models/vega

**Comment by geohot** [comment]
Woah, cool! Wonder who wrote the AMDGPU stuff

**Comment by AIFanatic** [comment]
Yeah written by amd https://github.com/gem5/gem5/commits?author=abmerop
abmerop is a computer architecture researcher at AMD Research.

Seems to be for vega but there are a few mentions of rdna https://github.com/gem5/gem5/blob/stable/src/arch/amdgpu/vega/insts/instructions.cc#L1312

Not sure if as interesting but also found this: https://bu-icsg.github.io/publications/2022/navisim_pact_2022.pdf
Another simulator in go: https://gitlab.com/akita/navisim/-/tree/master/rdnainsts
