### ISSUE TITLE
tools and links

### ISSUE THREAD

**Issue by smurfd** [geohot/7900xtx#3]
Radeon GPU analyzer
https://gpuopen.com/rga/

Radeon GPU profiler
https://gpuopen.com/rgp/

General Kernel gpu docs
https://docs.kernel.org/gpu/index.html?highlight=amd

llvm backend
https://llvm.org/docs/AMDGPUUsage.html

python interface for smi
https://rocmdocs.amd.com/projects/amdsmi/en/latest/py-interface_readme_link.html

searched for sdma, sometimes through the magnifying glass can find stuff om rocmdocs
https://rocmdocs.amd.com/en/latest/conceptual/gpu-memory.html

good comment about MES Locks
https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_mes.h#L403-L448

there is apparently this tool called systemtap in linux, here they have some good call diagrams as svg files. both under callgraph and rocm
https://github.com/jinsdb/amdgpu-systemtap-toolkit

some options to enable debugging for rocm 
https://rocmdocs.amd.com/en/develop/how-to/system-debugging.html

**Comment by Element115sw** [comment]
RDNA 3 ISA

https://www.amd.com/content/dam/amd/en/documents/radeon-tech-docs/instruction-set-architectures/rdna3-shader-instruction-set-architecture-feb-2023_0.pdf
